name: Postman Test - Playwground

on: [push]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: npm install -g newman

      - name: Install Newman reporter
        run: npm install newman-reporter-html

      - name: Run Postman collection
        run: |
          mkdir -p reports
          newman run collections/collection.json \
          -e environments/environment.json \
          --reporters cli,html,json \
          --reporter-html-export reports/report.html \
          --reporter-json-export reports/report.json

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: reports/
